version: '3'
services:
    es:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        environment:
            - cluster-name=SimplyStats-es
            - discovery.type=single-node
            - xpack.ml.enabled=false
            # - ES_TMPDIR=/data/elasticsearch/tmp
    db:
        image: rethinkdb:2.3.6
    bot:
        build: .
        env_file:
            - bot_vars.env
        depends_on:
            - es
            - db
