version: 2
jobs:
    test:
        working_directory: /opt/bot
        docker:
            - image: node:alpine
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Install system deps
                command: |
                    apk --no-cache add git
            - run:
                name: Install node deps
                command: |
                    npm i
            - run:
                name: Lint the code
                command: |
                    npm run test:lint
    deploy:
        working_directory: /opt/bot
        docker:
            - image: ubuntu:xenial
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "51:d7:2a:3c:88:c1:9e:fd:af:39:b0:28:2c:fe:84:b3"
            - run:
                name: Install SSH
                command: |
                    apt-get update && apt-get -y install ssh
            - run:
                name: Deploy to Production Server
                command: |
                    ssh -i prod.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SSH_HOST "git -C SimplyStats pull"
                    ssh -i prod.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SSH_HOST "cd SimplyStats; docker-compose stop bot"
                    ssh -i prod.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SSH_HOST "cd SimplyStats; docker-compose build"
                    ssh -i prod.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SSH_HOST "cd SimplyStats; docker-compose up -d --no-deps bot"
workflows:
    version: 2
    main:
        jobs:
            - test
            - deploy:
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^v\d+\.\d+\.\d+$/
