version: 2
jobs:
    test:
        working_directory: /opt/bot
        docker:
            - image: node:alpine
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Install system deps
                command: |
                    apk --no-cache add git
            - run:
                name: Install node deps
                command: |
                    npm i
            - run:
                name: Lint the code
                command: |
                    npm run test:lint
    deploy:
        working_directory: /opt/bot
        docker:
            - image: ubuntu:xenial
        steps:
            - run:
                name: Install SSH
                command: |
                    apt-get update && apt-get -y install ssh
            - run:
                name: Save SSH Key
                command: |
                    echo $SSH_KEY > prod.pem
            - run:
                name: Deploy to Production Server
                command: |
                    ssh -p prod.pem $SSH_USER@$SSH_HOST "git -C SimplyStats pull"
                    ssh -p prod.pem $SSH_USER@$SSH_HOST "cd SimplyStats; docker-compose stop"
                    ssh -p prod.pem $SSH_USER@$SSH_HOST "cd SimplyStats; docker-compose build"
                    ssh -p prod.pem $SSH_USER@$SSH_HOST "cd SimplyStats; docker-compose start"
workflows:
    version: 2
    main:
        jobs:
            - test
            - deploy:
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^v\d+\.\d+\.\d+$/
